version: "3.8"
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - 8007:15672
      - 8008:5672
    hostname: stats
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    environment:
    
      DEFAULT_USER: testingRabbit
      DEFAULT_PASS: testingRabbit
      DEFAULT_VHOST: 0.4
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host
volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge
    
  

      
      